### ISSUE TITLE
只能放在根目录运行

### ISSUE THREAD

**Issue by conanlg** [LC044/WeChatMsg#115]
**是否检查过issues没有相同问题**

**bug描述**
不放在根目录下运行，点击获取信息会报错

**报错截图**

**是否可复现**
可
**运行环境:**
 - OS: [e.g. Win10]
 - Python版本:
 - 软件版本: 
 - 微信版本:

**Additional context**
2023-12-11 14:01:47,750 - pc_decrypt.py[line:87] - ERROR: Traceback (most recent call last):
  File "app\ui_pc\tool\pc_decrypt\pc_decrypt.py", line 55, in get_info
  File "app\decrypt\get_wx_info.py", line 286, in get_info
  File "app\decrypt\get_wx_info.py", line 259, in read_info
  File "app\decrypt\get_wx_info.py", line 197, in get_key
  File "app\decrypt\get_wx_info.py", line 160, in verify_key
FileNotFoundError: [Errno 2] No such file or directory: 'None\\MSG\\MicroMsg.db'

**Comment by LC044** [comment]
试试最新代码能否解决该问题

**Comment by conanlg** [comment]
可以的

**Comment by conanlg** [comment]
臭宝牛逼
