### ISSUE TITLE
提升重新重启出现一下提示

### ISSUE THREAD

**Issue by SerenDipity-2023** [LC044/WeChatMsg#152]
**是否检查过issues没有相同问题**

**bug描述**
提升重新重启出现一下提示

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/130275049/31d46b70-e224-4128-b424-c15f450a5fb2)

**是否可复现**

**运行环境:**
 - OS: [e.g. Win10]
 - Python版本: 无 直接下载打包好的
 - 软件版本: MemoTrace-0.2.8
 - 微信版本:3.9.8.15

Exception: no such table: ContactHeadImg1
Traceback (most recent call last):
  File "main.py", line 60, in <module>
  File "main.py", line 39, in loadMainWinView
  File "app\ui\mainview.py", line 75, in __init__
  File "app\ui\mainview.py", line 92, in load_data
  File "app\ui\mainview.py", line 157, in set_my_info
  File "app\DataBase\misc.py", line 55, in get_avatar_buffer
sqlite3.OperationalError: no such table: ContactHeadImg1
2023-12-17 18:31:51,865 - main.py[line:66] - ERROR: None

**Comment by LC044** [comment]
删除app/database/msg文件夹重启微信再试试，可参考#136

**Comment by SerenDipity-2023** [comment]
可以了
