### ISSUE TITLE
启动报错：sqlite3.OperationalError: no such table: MSG

### ISSUE THREAD

**Issue by playmobil** [LC044/WeChatMsg#208]
把所有微信聊天从手机迁移到 PC ，大概 40 多 G
启动软件报错：sqlite3.OperationalError: no such table: MSG
所有的聊天只有 2022 年 12 月的

**Comment by weandy** [comment]
ValueError
ValueError: not enough values to unpack (expected 2, got 0)

Traceback (most recent call last)
File "flask\app.py", line 1478, in __call__
File "flask\app.py", line 1458, in wsgi_app
File "flask\app.py", line 1455, in wsgi_app
File "flask\app.py", line 869, in full_dispatch_request
File "flask\app.py", line 867, in full_dispatch_request
File "flask\app.py", line 852, in dispatch_request
File "app\web_ui\web.py", line 81, in christmas
ValueError: not enough values to unpack (expected 2, got 0)
This is the Copy/Paste friendly version of the traceback.

Traceback (most recent call last):
  File "flask\app.py", line 1478, in __call__
  File "flask\app.py", line 1458, in wsgi_app
  File "flask\app.py", line 1455, in wsgi_app
  File "flask\app.py", line 869, in full_dispatch_request
  File "flask\app.py", line 867, in full_dispatch_request
  File "flask\app.py", line 852, in dispatch_request
  File "app\web_ui\web.py", line 81, in christmas
ValueError: not enough values to unpack (expected 2, got 0)

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error. If you enable JavaScript you can also use additional features such as code execution (if the evalex feature is enabled), automatic pasting of the exceptions and much more.
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
Console Locked
The console is locked and needs to be unlocked by entering the PIN. You can find the PIN printed out on the standard output of your shell that runs the server.

PIN: 
 
我都是这样

**Comment by LC044** [comment]
试试新版能否解决该问题
