### ISSUE TITLE
遇到了一个bug：no such table: MSG

### ISSUE THREAD

**Issue by Rri-233** [LC044/WeChatMsg#228]
Traceback (most recent call last):
  File "F:\留痕\WeChatMsg-1.0.0\app\ui\tool\pc_decrypt\pc_decrypt.py", line 193, in btnExitClicked
    merge_databases(source_databases, target_database)
  File "F:\留痕\WeChatMsg-1.0.0\app\DataBase\merge.py", line 78, in merge_databases
    raise e
  File "F:\留痕\WeChatMsg-1.0.0\app\DataBase\merge.py", line 61, in merge_databases
    cursor.execute(sql)
sqlite3.OperationalError: no such table: MSG

**Comment by LC044** [comment]
重复issue
