### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by vc08932** [LC044/WeChatMsg#243]
**是否star** 是

**是否检查过issues没有相同问题** 是

**bug描述**
运行 `python main.py` 时，Python报错。
已经 Clone 最新版本的代码。
另附：上版本（https://github.com/LC044/WeChatMsg/tree/v0.2.8） 可以成功运行

**报错信息：**
```
Traceback (most recent call last):
  File "C:\Users\abc\Documents\WeChatMsg\main.py", line 12, in <module>
    from app.ui import mainview
  File "C:\Users\abc\Documents\WeChatMsg\app\ui\mainview.py", line 22, in <module>
    from .chat import ChatWindow
  File "C:\Users\abc\Documents\WeChatMsg\app\ui\chat\__init__.py", line 1, in <module>
    from .chat_window import ChatWindow
  File "C:\Users\abc\Documents\WeChatMsg\app\ui\chat\chat_window.py", line 10, in <module>
    from .chat_info import ChatInfo
  File "C:\Users\abc\Documents\WeChatMsg\app\ui\chat\chat_info.py", line 10, in <module>
    from app.util.emoji import get_emoji
  File "C:\Users\abc\Documents\WeChatMsg\app\util\emoji.py", line 79, in <module>
    class Emotion:
  File "C:\Users\abc\Documents\WeChatMsg\app\util\emoji.py", line 96, in Emotion
    def get_emoji_url(self, md5: str, thumb: bool) -> str | bytes:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**报错截图**
![image](https://github.com/LC044/WeChatMsg/assets/124547242/a0e0ef69-9408-4540-8a69-d9da48f04676)

**是否可复现** 可以

**运行环境:**
 - OS: [e.g. Win11] Win 10
 - Python版本: Python 3.9.9
 - 微信版本:3.9.8.25

**Additional context**
Release 的 MemoTrace-1.0.0.exe 运行后无反应，纯命令框，运行后生成若干文件，文件夹内皆无文件
```
├───2023-12-27-log.log
├───data
│   ├───emoji
│   ├───image
│   └───聊天记录
├───MemoTrace-1.0.0.exe
```
![image](https://github.com/LC044/WeChatMsg/assets/124547242/b18dbcba-a1d3-4efd-bd71-38eb13522a99)

**Comment by LC044** [comment]
最新代码要求python>=3.10

**Comment by LC044** [comment]
在使用文档第一步已经注明python版本，可以再仔细阅读一下文档

**Comment by LC044** [comment]
exe文件无反应可以重启一下电脑试试
