### ISSUE TITLE
[Bug] 无法导出成word

### ISSUE THREAD

**Issue by wgll000** [LC044/WeChatMsg#297]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

3.11

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

源码

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/87935282/41d624e1-eb67-4016-9477-ec5232530377)
2024-01-11 21:48:53,120 - main.py[line:16] - ERROR: 程序发生了错误:

Exception Type: ValueError
Exception Value: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
details: Traceback (most recent call last):
  File "D:\Users\Downloads\WeChatMsg-master\app\DataBase\output.py", line 105, in run
    self.export()
  File "D:\Users\Downloads\WeChatMsg-master\app\DataBase\exporter_docx.py", line 315, in export
    self.text(doc, message)
  File "D:\Users\Downloads\WeChatMsg-master\app\DataBase\exporter_docx.py", line 32, in text
    content_cell.paragraphs[0].add_run(str_content)
  File "C:\Users\Administrator\anaconda3\envs\WeChatMsg-master\Lib\site-packages\docx\text\paragraph.py", line 45, in add_run
    run.text = text
    ^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\WeChatMsg-master\Lib\site-packages\docx\text\run.py", line 217, in text
    self._r.text = text
    ^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\WeChatMsg-master\Lib\site-packages\docx\oxml\text\run.py", line 130, in text
    _RunContentAppender.append_to_run_from_text(self, text)
  File "C:\Users\Administrator\anaconda3\envs\WeChatMsg-master\Lib\site-packages\docx\oxml\text\run.py", line 251, in append_to_run_from_text
    appender.add_text(text)
  File "C:\Users\Administrator\anaconda3\envs\WeChatMsg-master\Lib\site-packages\docx\oxml\text\run.py", line 256, in add_text
    self.add_char(char)
  File "C:\Users\Administrator\anaconda3\envs\WeChatMsg-master\Lib\site-packages\docx\oxml\text\run.py", line 270, in add_char
    self.flush()
  File "C:\Users\Administrator\anaconda3\envs\WeChatMsg-master\Lib\site-packages\docx\oxml\text\run.py", line 278, in flush
    self._r.add_t(text)
  File "C:\Users\Administrator\anaconda3\envs\WeChatMsg-master\Lib\site-packages\docx\oxml\text\run.py", line 41, in add_t
    t = self._add_t(text=text)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\WeChatMsg-master\Lib\site-packages\docx\oxml\xmlchemy.py", line 309, in _add_child
    setattr(child, key, value)
  File "src\\lxml\\etree.pyx", line 1048, in lxml.etree._Element.text.__set__
  File "src\\lxml\\apihelpers.pxi", line 749, in lxml.etree._setNodeText
  File "src\\lxml\\apihelpers.pxi", line 737, in lxml.etree._createTextNode
  File "src\\lxml\\apihelpers.pxi", line 1530, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

### 🚦 期望结果 | Expected Behavior

导出成功

### 📷 复现步骤 | Recurrence Steps

安装完依赖后打开程序，解密数据库后无法正常导出

**Comment by LC044** [comment]
能把出错的这一条消息发一下吗

**Comment by LC044** [comment]
试试最新代码

**Comment by wgll000** [comment]
你好，最新代码再次出现报错
2024-01-12 14:53:36,980 - exporter_docx.py[line:60] - ERROR: 非法字符:蓝桥杯大赛报名已接近尾声，请同学们转告身边还有意向报名的同学抓紧时间报名。下周将进入集中审核、交纳报名费的阶段。现有几点重要通知：
1、计算机学院将调整蓝桥杯（属于C类赛事）软件赛A、B组获奖在学科竞赛加分时的加分力度：适当调高A组加分分值，降低B组加分分值。其他赛道的加分政策不变，仍按C类竞赛加分。具体调整力度需等学院党政联席会议讨论决定。
2、如有需要修改报名信息（如从B组换到A组）的，请尽快完成修改。学院审核、交费完成后不可更改。
3、报名费交纳：
情况一：已找好指导老师，请将报名费交给指导老师，由指导老师本人或指定一名学生将所带全部学生的名单、报名费、开票金额和张数一起交给我。
情况二：未找指导老师的，将由我（王婷老师）作为指导老师，请将报名费直接转给我（支付宝账号：@139.com）,请务必备注好班级、姓名、参赛组别和是否需要发票！！！
2024-01-12 14:53:36,985 - main.py[line:16] - ERROR: 程序发生了错误:

Exception Type: ValueError
Exception Value: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
details: Traceback (most recent call last):
  File "D:\Users\Downloads\WeChatMsg-master\app\DataBase\exporter_docx.py", line 58, in text
    content_cell.paragraphs[0].add_run(str_content)
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\text\paragraph.py", line 45, in add_run
    run.text = text
    ^^^^^^^^
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\text\run.py", line 217, in text
    self._r.text = text
    ^^^^^^^^^^^^
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 130, in text
    _RunContentAppender.append_to_run_from_text(self, text)
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 251, in append_to_run_from_text
    appender.add_text(text)
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 256, in add_text
    self.add_char(char)
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 270, in add_char
    self.flush()
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 278, in flush
    self._r.add_t(text)
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 41, in add_t
    t = self._add_t(text=text)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\xmlchemy.py", line 309, in _add_child
    setattr(child, key, value)
  File "src\\lxml\\etree.pyx", line 1048, in lxml.etree._Element.text.__set__
  File "src\\lxml\\apihelpers.pxi", line 749, in lxml.etree._setNodeText
  File "src\\lxml\\apihelpers.pxi", line 737, in lxml.etree._createTextNode
  File "src\\lxml\\apihelpers.pxi", line 1530, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Downloads\WeChatMsg-master\app\DataBase\output.py", line 105, in run
    self.export()
  File "D:\Users\Downloads\WeChatMsg-master\app\DataBase\exporter_docx.py", line 357, in export
    self.text(doc, message)
  File "D:\Users\Downloads\WeChatMsg-master\app\DataBase\exporter_docx.py", line 62, in text
    content_cell.paragraphs[0].add_run(str_content)
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\text\paragraph.py", line 45, in add_run
    run.text = text
    ^^^^^^^^
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\text\run.py", line 217, in text
    self._r.text = text
    ^^^^^^^^^^^^
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 130, in text
    _RunContentAppender.append_to_run_from_text(self, text)
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 251, in append_to_run_from_text
    appender.add_text(text)
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 256, in add_text
    self.add_char(char)
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 270, in add_char
    self.flush()
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 278, in flush
    self._r.add_t(text)
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\text\run.py", line 41, in add_t
    t = self._add_t(text=text)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Downloads\WeChatMsg-master\venv\Lib\site-packages\docx\oxml\xmlchemy.py", line 309, in _add_child
    setattr(child, key, value)
  File "src\\lxml\\etree.pyx", line 1048, in lxml.etree._Element.text.__set__
  File "src\\lxml\\apihelpers.pxi", line 749, in lxml.etree._setNodeText
  File "src\\lxml\\apihelpers.pxi", line 737, in lxml.etree._createTextNode
  File "src\\lxml\\apihelpers.pxi", line 1530, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

**Comment by wgll000** [comment]
数据已做脱敏处理

**Comment by wgll000** [comment]
已知可能出现问题的字符为
字符： 
Unicode(HEX)： 0014
Unicode(十进制)： 20
所在范围： 无
期望改进

**Comment by LC044** [comment]
再试试
