### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by JackieGLQ** [LC044/WeChatMsg#322]
### 👌 是否检查过没有类似issue

就不检查

### 🧐 问题描述 | Proposed Solution

执行python main.py 命令后提示如下错误：
2024-01-17 20:06:12,616 - main.py[line:16] - ERROR: 程序发生了错误:

Exception Type: TypeError
Exception Value: unsupported operand type(s) for |: 'type' and 'type'
details: Traceback (most recent call last):
  File "E:\GaoLLM\Test\WeChatMsg\WeChatMsg\main.py", line 31, in <module>
    from app.ui import mainview
  File "E:\GaoLLM\Test\WeChatMsg\WeChatMsg\app\ui\mainview.py", line 21, in <module>
    from .chat import ChatWindow
  File "E:\GaoLLM\Test\WeChatMsg\WeChatMsg\app\ui\chat\__init__.py", line 1, in <module>
    from .chat_window import ChatWindow
  File "E:\GaoLLM\Test\WeChatMsg\WeChatMsg\app\ui\chat\chat_window.py", line 10, in <module>
    from .chat_info import ChatInfo
  File "E:\GaoLLM\Test\WeChatMsg\WeChatMsg\app\ui\chat\chat_info.py", line 10, in <module>
    from app.util.emoji import get_emoji
  File "E:\GaoLLM\Test\WeChatMsg\WeChatMsg\app\util\emoji.py", line 94, in <module>
    class Emotion:
  File "E:\GaoLLM\Test\WeChatMsg\WeChatMsg\app\util\emoji.py", line 111, in Emotion
    def get_emoji_url(self, md5: str, thumb: bool) -> str | bytes:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

QWidget: Must construct a QApplication before a QWidget
请问是什么原因呢？

**Comment by LC044** [comment]
没有其他报错吗

**Comment by reinfforce** [comment]
我也是这个报错。运行main.py之后的报错

**Comment by LC044** [comment]
> 我也是这个报错。运行main.py之后的报错

仔细阅读文档，python>=3.10
