### ISSUE TITLE
[Bug] 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by sigma39** [LC044/WeChatMsg#348]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

3.11

### 💻 微信版本

3.9.8.25

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/78814530/90aff544-bc82-420b-93e7-a42324973b36)
C:\Users\Administrator\Desktop\WeChatMsg-master>main.py
Exception: 'NoneType' object is not subscriptable
2024-01-30 13:59:30,334 - main.py[line:116] - ERROR: Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\WeChatMsg-master\main.py", line 110, in <module>
    view.loadMainWinView()
  File "C:\Users\Administrator\Desktop\WeChatMsg-master\main.py", line 81, in loadMainWinView
    self.viewMainWindow = mainview.MainWinController(username=username)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\WeChatMsg-master\app\ui\mainview.py", line 273, in __init__
    self.load_data()
  File "C:\Users\Administrator\Desktop\WeChatMsg-master\app\ui\mainview.py", line 299, in load_data
    self.set_my_info(wxid)
  File "C:\Users\Administrator\Desktop\WeChatMsg-master\app\ui\mainview.py", line 354, in set_my_info
    me.smallHeadImgUrl = contact_info_list[7]
                         ~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

### 🚦 期望结果 | Expected Behavior

_No response_

### 📷 复现步骤 | Recurrence Steps

解密正常，再次打开报错

### 📝 补充信息 | Additional Information

_No response_

**Comment by LC044** [comment]
重启了没

**Comment by sigma39** [comment]
> 重启了没

重启过了，也尝试更新了微信版本，测试了1.04-1.07版本都是类似问题

**Comment by LC044** [comment]
重新解密试试
