### ISSUE TITLE
[Bug] 长聊天记录导出崩溃

### ISSUE THREAD

**Issue by liangraiden** [LC044/WeChatMsg#363]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

None

### 💻 微信版本

None

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

报错截图:
2024-02-05 13:53:02,030 - output.py[line:389] - ERROR: Traceback (most recent call last):
  File "app\DataBase\output.py", line 383, in run
  File "app\util\image.py", line 106, in get_image
  File "app\util\image.py", line 72, in decode_dat
  File "app\util\image.py", line 72, in <listcomp>
MemoryError

2024-02-05 13:53:02,079 - media_msg.py[line:105] - ERROR: 语音发送错误
Traceback (most recent call last):
  File "app\DataBase\media_msg.py", line 93, in get_audio
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1456, in _execute_child
OSError: [WinError 8] 内存资源不足，无法处理此命令。

**Comment by LC044** [comment]
估计是你内存太小了，软件大概会占用1G内存
