### ISSUE TITLE
[Bug] 3.9.9.43 版（最新版）微信，提示数据库合并错误

### ISSUE THREAD

**Issue by RockNHawk** [LC044/WeChatMsg#380]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

None

### 💻 微信版本

最新版

### 软件版本 | EXE Version

我是找茬的

### 🐛 问题描述 | Bug Description

报错截图:

如图，获取信息正常，点击开始，进度到 100% 后，提示如下错误（我并没有双开微信，只打开了一个微信实例）。

![image](https://github.com/LC044/WeChatMsg/assets/3222379/994a4f37-fd08-4bbd-836f-62e887c14497)

再次启动程序，就假死了，完整日志如下：

2024-02-23 17:23:45,664 - pc_decrypt.py[line:248] - ERROR: Traceback (most recent call last):
  File "app\ui\tool\pc_decrypt\pc_decrypt.py", line 246, in run
  File "shutil.py", line 434, in copy2
  File "shutil.py", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: './app/Database/Msg\\MSG0.db'

2024-02-23 17:23:45,813 - merge.py[line:77] - ERROR: ./app/Database/Msg\MSG1.db数据库合并错误:
Traceback (most recent call last):
  File "app\DataBase\merge.py", line 70, in merge_databases
sqlite3.OperationalError: no such table: MSG

2024-02-23 17:23:45,832 - pc_decrypt.py[line:266] - ERROR: Traceback (most recent call last):
  File "app\ui\tool\pc_decrypt\pc_decrypt.py", line 264, in run
  File "shutil.py", line 434, in copy2
  File "shutil.py", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: './app/Database/Msg\\MediaMSG0.db'

2024-02-23 17:24:43,482 - main.py[line:20] - ERROR: 程序发生了错误:

Exception Type: OperationalError
Exception Value: no such table: MSG
details: Traceback (most recent call last):
  File "app\ui\chat\chat_window.py", line 148, in run
  File "app\DataBase\micro_msg.py", line 79, in get_contact
  File "app\DataBase\msg.py", line 395, in get_contact
sqlite3.OperationalError: no such table: MSG

数据库错误，请删除app文件夹后重启电脑再运行软件

您可添加QQ群发送log文件以便解决该问题
2024-02-23 17:25:02,607 - main.py[line:20] - ERROR: 程序发生了错误:

Exception Type: OperationalError
Exception Value: no such table: MSG
details: Traceback (most recent call last):
  File "app\ui\chat\chat_window.py", line 148, in run
  File "app\DataBase\micro_msg.py", line 79, in get_contact
  File "app\DataBase\msg.py", line 395, in get_contact
sqlite3.OperationalError: no such table: MSG

数据库错误，请删除app文件夹后重启电脑再运行软件

您可添加QQ群发送log文件以便解决该问题

### 📷 复现步骤 | Recurrence Steps

步骤如上，重新试过几次，重启电脑，都是如此。

**Comment by RockNHawk** [comment]
补充：
我在 Windows sandbox 里，全新安装最新微信，提示成功，但是重启无聊天记录。

不过，我另外在一个虚拟机里，用老版本微信（3.8），可以成功读取到微信聊天记录~

**Comment by LinLi-DL** [comment]
我也出现这个问题

**Comment by LC044** [comment]
多试几次就行了
