### ISSUE TITLE
[Bug] 经常报错闪退

### ISSUE THREAD

**Issue by ZX828** [LC044/WeChatMsg#424]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

None

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![image](https://github.com/LC044/WeChatMsg/assets/144084680/464c829b-86d6-4b7c-bf00-8ff4d7829b21)
顺便提一句，电脑直接卡住，截图都费劲。

### 📷 复现步骤 | Recurrence Steps

让我删除app，重新登录或者卸载微信重装。
我卸载重装了，然后，一启动就这样了。
我重新解压了，并且重新安装微信了。下载的新版微信。

### 📝 补充信息 | Additional Information

2024-04-19 19:34:25,166 - misc.py[line:70] - ERROR: 数据库错误
Traceback (most recent call last):
  File "app\DataBase\misc.py", line 64, in get_avatar_buffer
sqlite3.OperationalError: no such table: ContactHeadImg1

2024-04-19 19:34:41,564 - main.py[line:20] - ERROR: 程序发生了错误:

Exception Type: ProgrammingError
Exception Value: Cannot operate on a closed database.
details: version:2.0.6
Traceback (most recent call last):
  File "exporter\\exporter_pyq.py", line 48, in exporter_pyq.PYQExporter.run
  File "exporter\\exporter_pyq.py", line 94, in exporter_pyq.PYQExporter.to_html
  File "app\DataBase\sns.py", line 79, in get_sns_bg_url
sqlite3.ProgrammingError: Cannot operate on a closed database.

数据库错误，请删除app文件夹后重启电脑再运行软件

您可添加QQ群:548409157发送log文件以便解决该问题
2024-04-19 19:37:19,814 - main.py[line:20] - ERROR: 程序发生了错误:

Exception Type: AttributeError
Exception Value: 'NoneType' object has no attribute 'close'
details: version:2.0.6
Traceback (most recent call last):
  File "app\ui\chat\chat_window.py", line 159, in run
  File "app\DataBase\__init__.py", line 35, in close_db
  File "app\DataBase\media_msg.py", line 159, in close
AttributeError: 'NoneType' object has no attribute 'close'

未知错误类型，可参考 https://memotrace.cn/doc/posts/error/faq.html 解决该问题
温馨提示：重启电脑可解决80%的问题

您可添加QQ群:548409157发送log文件以便解决该问题

**Comment by LC044** [comment]
请删除app文件夹后重启电脑再运行软件应该能解决问题
