### ISSUE TITLE
[Bug]  未知错误

### ISSUE THREAD

**Issue by auroralzone** [LC044/WeChatMsg#468]
### 👌 是否需要解答

是

### 👌 是否检查过没有类似issue

否

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

None

### 软件版本 | EXE Version

Other

### 🐛 问题描述 | Bug Description

![image](https://github.com/LC044/WeChatMsg/assets/42070770/caf68347-cdd8-4bfa-8e48-9043e2daaaaa)

### 📝 补充信息 | Additional Information

```log
2024-06-01 15:44:58,150 - pc_decrypt.py[line:355] - ERROR: Traceback (most recent call last):
  File "psutil\_pswindows.py", line 902, in memory_maps
PermissionError: [WinError 5] 拒绝访问。: '(originated from OpenProcess)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\ui\tool\pc_decrypt\pc_decrypt.py", line 337, in run
  File "app\decrypt\get_wx_info.py", line 441, in get_info
  File "app\decrypt\get_wx_info.py", line 371, in read_info
  File "psutil\__init__.py", line 1187, in memory_maps
  File "psutil\__init__.py", line 1187, in <listcomp>
  File "psutil\_pswindows.py", line 906, in memory_maps
psutil.AccessDenied: (pid=33560, name='WeChat.exe')
```

**Comment by LC044** [comment]
多试几次就行了
