### ISSUE TITLE
运行后提示文件找不到

### ISSUE THREAD

**Issue by cruelsummer5** [LC044/WeChatMsg#50]
2023-12-04 16:31:09,293 - pc_decrypt.py[line:87] - ERROR: Traceback (most recent call last):
  File "app\ui_pc\tool\pc_decrypt\pc_decrypt.py", line 75, in get_info
  File "app\util\path.py", line 27, in wx_path
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\test\\AppData\\Roaming\\Tencent\\WeChat\\All Users\\config\\3ebffe94.ini'

**Comment by LC044** [comment]
最新代码已经解决该问题，可以试试

**Comment by AmandaloveYang** [comment]
![Uploading 789ccfd5a4be5cbe2a8e9d3b9da335f.png…]()
