### ISSUE TITLE
[Bug] 获取信息提示：未知错误

### ISSUE THREAD

**Issue by 991547436** [LC044/WeChatMsg#541]
### 👌 是否需要解答

否

### 👌 是否检查过没有类似issue

是

### 💻 Python版本

我用的EXE程序

### 💻 微信版本

最新版

### 软件版本 | EXE Version

最新版

### 🐛 问题描述 | Bug Description

报错截图:
![微信图片_20241226150024](https://github.com/user-attachments/assets/fe3b3f7f-eb06-48ee-852b-e5b4fa52193a)

MemoTrace-2.0.16.exe会报错，clone下来的项目可以正常获取信息

### 🚦 期望结果 | Expected Behavior

正常执行

### 📷 复现步骤 | Recurrence Steps

打开MemoTrace.exe（与是否管理员无关），点击获取信息

### 📝 补充信息 | Additional Information

2024-12-26 14:52:36,593 - pc_decrypt.py[line:531] - ERROR: Traceback (most recent call last):
  File "win32com\client\dynamic.py", line 80, in _GetGoodDispatch
pywintypes.com_error: (-2147221008, '尚未调用 CoInitialize。', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\ui\tool\pc_decrypt\pc_decrypt.py", line 511, in run
  File "app\decrypt\get_wx_info.py", line 439, in get_info
  File "app\decrypt\get_wx_info.py", line 368, in read_info
  File "win32com\client\__init__.py", line 114, in Dispatch
  File "win32com\client\dynamic.py", line 100, in _GetGoodDispatchAndUserName
  File "win32com\client\dynamic.py", line 82, in _GetGoodDispatch
pywintypes.com_error: (-2147221008, '尚未调用 CoInitialize。', None, None)

**Comment by holmesian** [comment]
一摸一样的问题。

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\ui\tool\pc_decrypt\pc_decrypt.py", line 511, in run
  File "app\decrypt\get_wx_info.py", line 439, in get_info
  File "app\decrypt\get_wx_info.py", line 368, in read_info
  File "win32com\client\__init__.py", line 114, in Dispatch
  File "win32com\client\dynamic.py", line 100, in _GetGoodDispatchAndUserName
  File "win32com\client\dynamic.py", line 82, in _GetGoodDispatch
pywintypes.com_error: (-2147221008, '尚未调用 CoInitialize。', None, None)
```

**Comment by LC044** [comment]
更新到2.1.0试试
