### ISSUE TITLE
sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by microrole** [LC044/WeChatMsg#86]
**bug描述**
首次运行解密成功后，再次打开，报错：
Traceback (most recent call last):
  File "app\ui_pc\chat\chat_window.py", line 135, in run
  File "app\DataBase\micro_msg.py", line 60, in get_contact
sqlite3.DatabaseError: database disk image is malformed
**报错截图**

**是否可复现**
一直闪退
**运行环境:**
 - OS: win11
 - Python版本: Python 3.10.11
 - 软件版本:  MemoTrace-0.2.6.exe
 - 微信版本: 3.9.7.29

**Comment by LC044** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/95485601/16b93320-33da-441c-b35b-3f5c2a2988a9)

**Comment by microrole** [comment]
![image](https://github.com/LC044/WeChatMsg/assets/152576234/e9fde729-4e51-4a48-b80b-223beac9399c)
更新到最新版还是不行
![image](https://github.com/LC044/WeChatMsg/assets/152576234/e235bc36-b561-40ff-be8e-499a70148aa6)

**Comment by LC044** [comment]
看看图里那个项目，看他的能解密不
